version: '3.9'
services:
  postgresqldb:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=speedyauth

  migratedb:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:root@postgresqldb:5432/speedyauth?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - postgresqldb
    links:
     - postgresqldb
    restart: on-failure

  app:
    depends_on:
      - postgresqldb
      - migratedb
    build: .
    restart: always
    ports:
     - "8080:8080"
    environment:
      - PG_HOST=postgresqldb
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=speedyauth
      - PG_PORT=5432
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SERVER_PORT=8080
      - SERVER_ADDRESS=
      - PG_SSL=False
      - TOKEN_EXPIRY_TIME=15m
      - ISSUER_NAME=localhost
      - FROM_EMAIL_ADDRESS=noreply@localhost

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025